name: skyline_university

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the versions and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.6.0+22

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  overlay_support: ^1.0.2
  gradient_app_bar: ^0.1.3
  firebase_messaging: ^6.0.9
  font_awesome_flutter: ^8.5.0
  url_launcher: ^5.4.1
  flutter_spinkit: ^4.1.1+1
  transparent_image: ^1.0.0
  carousel_slider: ^1.4.0
  datetime_picker_formfield: ^1.0.0
  superellipse_shape: ^0.1.5
  flutter_screenutil: ^0.7.0
  path_provider: ^1.5.1
  esys_flutter_share: ^1.0.2
  photo_view: ^0.9.0
  shared_preferences: ^0.5.6+1
  flutter_html: ^0.11.1
  google_maps_flutter: ^0.5.21
  youtube_player_flutter: ^6.0.3+2
  # flutter_calendar_carousel: ^1.4.10 
  date_utils: ^0.1.0+3
  #TODO: cahnge to local
  flushbar: ^1.9.1
  cupertino_icons: ^0.1.2
  selection_menu: ^0.9.0
  translator: ^0.1.4
  pdf_viewer_plugin: ^1.0.0+2
  # webview_flutter: ^0.3.19+4
  flutter_webview_plugin: ^0.3.10+1
  quick_actions: ^0.4.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/launcher.png"
  

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  #   To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images-white/
    - images/launcher.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Skyline
  #     fonts:
  #       - asset: fonts/Skyline.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
