name: skyline_university

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the versions and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.6.0+41

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  overlay_support: ^1.0.2
  gradient_app_bar: ^0.1.3
  new_gradient_app_bar: ^0.2.0
  firebase_messaging: ^11.2.6
  firebase_core: ^1.12.0
  flutter_local_notifications: ^9.2.0
  font_awesome_flutter: ^9.2.0
  url_launcher: ^6.0.18
  sticky_headers: ^0.2.0
  local_auth: ^1.1.10
  # local_auth:
  #   # git:
  #   #   url: git://github.com/soosafe/plugins.git
  #   #   path: packages/local_auth/

  # # https://github.com/kennethj/flutter-plugins/tree/master/packages/local_auth
  # # https://github.com/kennethj/flutter-plugins.git
  # # local_auth: 1.1.0-nullsafety
  flutter_spinkit: ^5.1.0
  transparent_image: ^2.0.0
  carousel_slider: ^4.0.0
  datetime_picker_formfield: ^2.0.0
  superellipse_shape: ^0.2.0
  path_provider: ^1.1.0
  # # esys_flutter_share: ^1.0.2
  esys_flutter_share:
    git:
      url: git://github.com/jawad12345A/esys-flutter-share.git
  photo_view: ^0.13.0
  shared_preferences: ^2.0.12
  flutter_html: ^2.2.1
  google_maps_flutter: ^2.1.1
  date_utils: ^0.2.0
  # # discontinued
  flushbar: ^1.10.4
  # # End
  cupertino_icons: ^1.0.4
  selection_menu: ^1.0.0
  translator: ^0.1.7
  pdf_viewer_plugin: ^2.0.1
  syncfusion_flutter_pdfviewer: ^19.4.47-beta
  flutter_webview_plugin: ^0.4.0
  # webview_flutter: ^3.0.0
  quick_actions: ^0.6.0+9
  flutter_dynamic_icon: ^2.0.0
  # html: ^0.15.0
  skeleton_loader: ^2.0.0+4
  youtube_player_flutter: ^8.0.0
  chips_choice: ^2.0.1
  toggle_switch: ^1.4.0
  roundcheckbox: ^2.0.4+1
  http: ^0.13.4
  flutter_toggle_tab: ^1.1.7
  flutter_pay: ^1.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  # flutter_launcher_name: ^0.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/launcher.png"
# flutter_launcher_name:
#   name: "SkylineUniversity"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  #   To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images-white/
    - images/launcher.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Skyline
  #     fonts:
  #       - asset: fonts/Skyline.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
